services:
  mysql:
    image: mysql:8.0
    container_name: course-registration-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: course_registration_system
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - course_registration_mysql_data:/var/lib/mysql

volumes:
  course_registration_mysql_data:
